const combinations = [
    "Kappa TriHard MaxLOL",
    "Kappa TriHard DansGame",
    "Kappa TriHard Jebaited",
    "Kappa TriHard Kreygasm",
    "Kappa MaxLOL DansGame",
    "Kappa MaxLOL Jebaited",
    "Kappa MaxLOL Kreygasm",
    "Kappa DansGame Jebaited",
    "Kappa DansGame Kreygasm",
    "Kappa Jebaited Kreygasm",
    "TriHard MaxLOL DansGame",
    "TriHard MaxLOL Jebaited",
    "TriHard MaxLOL Kreygasm",
    "TriHard DansGame Jebaited",
    "TriHard DansGame Kreygasm",
    "TriHard Jebaited Kreygasm",
    "MaxLOL DansGame Jebaited",
    "MaxLOL DansGame Kreygasm",
    "MaxLOL Jebaited Kreygasm",
    "DansGame Jebaited Kreygasm",
    "Kappa TriHard MaxLOL",
    "Kappa TriHard DansGame",
    "Kappa TriHard Jebaited",
    "Kappa TriHard Kreygasm",
    "Kappa MaxLOL DansGame",
    "Kappa MaxLOL Jebaited",
    "Kappa MaxLOL Kreygasm",
    "Kappa DansGame Jebaited",
    "Kappa DansGame Kreygasm",
    "Kappa Jebaited Kreygasm",
    "TriHard MaxLOL DansGame",
    "TriHard MaxLOL Jebaited",
    "TriHard MaxLOL Kreygasm",
    "TriHard DansGame Jebaited",
    "TriHard DansGame Kreygasm",
    "TriHard Jebaited Kreygasm",
    "MaxLOL DansGame Jebaited",
    "MaxLOL DansGame Kreygasm",
    "MaxLOL Jebaited Kreygasm",
    "DansGame Jebaited Kreygasm",
    "Kappa TriHard MaxLOL",
    "Kappa TriHard DansGame",
    "Kappa TriHard Jebaited",
    "Kappa TriHard Kreygasm",
    "Kappa MaxLOL DansGame",
    "Kappa MaxLOL Jebaited",
    "Kappa MaxLOL Kreygasm",
    "Kappa DansGame Jebaited",
    "Kappa DansGame Kreygasm",
    "Kappa Jebaited Kreygasm",
    "TriHard MaxLOL DansGame",
    "TriHard MaxLOL Jebaited",
    "TriHard MaxLOL Kreygasm",
    "TriHard DansGame Jebaited",
    "TriHard DansGame Kreygasm",
    "TriHard Jebaited Kreygasm",
    "MaxLOL DansGame Jebaited",
    "MaxLOL DansGame Kreygasm",
    "MaxLOL Jebaited Kreygasm",
    "DansGame Jebaited Kreygasm",
    "Kappa TriHard MaxLOL",
    "Kappa TriHard DansGame",
    "Kappa TriHard Jebaited",
    "Kappa TriHard Kreygasm",
    "Kappa MaxLOL DansGame",
    "Kappa MaxLOL Jebaited",
    "Kappa MaxLOL Kreygasm",
    "Kappa DansGame Jebaited",
    "Kappa DansGame Kreygasm",
    "Kappa Jebaited Kreygasm",
    "TriHard MaxLOL DansGame",
    "TriHard MaxLOL Jebaited",
    "TriHard MaxLOL Kreygasm",
    "TriHard DansGame Jebaited",
    "TriHard DansGame Kreygasm",
    "TriHard Jebaited Kreygasm",
    "MaxLOL DansGame Jebaited",
    "MaxLOL DansGame Kreygasm",
    "MaxLOL Jebaited Kreygasm",
    "DansGame Jebaited Kreygasm",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Jebaited Jebaited Jebaited",
    "Kappa Kappa Kappa",
    "Kappa Kappa Kappa",
    "Kappa Kappa Kappa",
    "Kappa Kappa Kappa",
    "Kappa Kappa Kappa",
    "Kappa Kappa Kappa",
    "Kappa Kappa Kappa",
    "MaxLOL MaxLOL MaxLOL",
    "MaxLOL MaxLOL MaxLOL",
    "MaxLOL MaxLOL MaxLOL",
    "MaxLOL MaxLOL MaxLOL",
    "MaxLOL MaxLOL MaxLOL",
    "MaxLOL MaxLOL MaxLOL",
    "MaxLOL MaxLOL MaxLOL",
    "DansGame DansGame DansGame",
    "DansGame DansGame DansGame",
    "DansGame DansGame DansGame",
    "DansGame DansGame DansGame",
    "DansGame DansGame DansGame",
    "DansGame DansGame DansGame",
    "DansGame DansGame DansGame",
    "TriHard TriHard TriHard",
    "TriHard TriHard TriHard",
    "TriHard TriHard TriHard",
    "TriHard TriHard TriHard",
    "Kreygasm Kreygasm Kreygasm",
    "Kreygasm Kreygasm Kreygasm",
  ];
  if (commandName === '!spin') {
    const num = randomIndex();
    client.say(target, `You rolled a ${num}`);
    console.log(`* Executed ${commandName} command`);
  } else {
    console.log(`* Unknown command ${commandName}`);
  }

 function randomIndex(){
    var index = Math.floor(Math.random() * (combinations.length) + 1);
    console.log(combinations[index])
    return combinations[index];
}


randomIndex();



